apiVersion: inwinstack.com/v1
kind: Pool
metadata:
  name: test
spec:
  CIDR: 172.22.132.0/24
  addresses:
  - 172.22.132.0-172.22.132.15
  - 172.22.132.250-172.22.132.255
  gateway: 172.22.132.1
  assignToNamespace: false
  filterIPs:
  - 172.22.132.10
  avoidBuggyIPs: true
  avoidGatewayIPs: true
  ignoreNamespaceAnnotation: true
  ignoreNamespaces:
  - kube-system
  - kube-public
  - default
